name: dopamine_detox
description: Dopamine Detox, Habit Builder & Health App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  device_apps: ^2.2.0
  permission_handler: ^11.3.1
  flutter_overlay_window: ^0.4.2
  in_app_purchase: ^3.1.13
  smooth_page_indicator: ^1.1.0
  
  # Pedometer ka Purana Version (Jo SDK 35 nahi mangega)
  pedometer: 3.0.0
  
  lottie: ^3.1.2
  cached_network_image: ^3.3.1
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
