uploads = []
generated = []

[[outputs]]
id = "aPVHX-IB8KvFu861-8U1F"
uri = "file://flutter_dopamine_detox.tar.gz"
type = "unspecified"
title = "Dopamine Detox Flutter Project"

[[outputs]]
id = "xxwyztC4-vPsFxVuLrerz"
uri = "file://flutter_dopamine_detox_FINAL.tar.gz"
type = "unspecified"
title = "Dopamine Detox — FINAL Production Build"

[[outputs]]
id = "bDuyFHi0g1AK5BLduuJPl"
uri = "file://flutter_dopamine_detox_WITH_GITHUB_ACTIONS.tar.gz"
type = "unspecified"
title = "Dopamine Detox — Complete Project + GitHub Actions"

[[outputs]]
id = "xnIZqygy-9GF9aQerETmH"
uri = "file://flutter_dopamine_detox_v2.tar.gz"
type = "unspecified"
title = "Dopamine Detox v2 — All 5 Features Updated"
