name: Build Android APK

on:
  push:
    branches: [ "Merge-app" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Update Ads & Build App
        run: |
          PUBSPEC=$(find . -name "pubspec.yaml" | head -n 1)
          DIR=$(dirname "$PUBSPEC")
          cd "$DIR"
          
          # 1. Purani cache saaf karein
          flutter clean
          
          # 2. SABSE ZAROORI: Ads wale package ko automatically update karein
          flutter pub add google_mobile_ads
          
          # 3. Naye system ke hisaab se Android files banayein
          flutter create .
          
          # 4. Saare naye packages download karein
          flutter pub get
          
          # 5. Final APK Build karein
          flutter build apk --release --no-shrink
          
          mkdir -p $GITHUB_WORKSPACE/output
          find build -name "*.apk" -exec cp {} $GITHUB_WORKSPACE/output/ \;
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Mera-Game-APK
          path: output/*.apk
